<?php
/**
 * Created by PhpStorm.
 * User: wowucco
 * Date: 16.07.16
 * Time: 0:39
 */

namespace app\components\citations;

use app\components\citations\models\Citations;
use yii\base\Widget;

class CitationsWidget extends Widget
{

   /* public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }*/

    private $citation;
    
    private function getRandomCitation()
    {
        $this->citation = $this->getAllCitations();
        return $this->citation[array_rand($this->citation, 1)];
    }

    private function getAllCitations()
    {
        return Citations::find()->all();
    }
    
    public function run()
    {
        return $this->render('index', ['citation' => $this->getRandomCitation()]);
    }
}